#!/usr/bin/env python

import sys
try:
	import pygtk
	pygtk.require("2.0")
except:
	pass
try:
	import gtk
	import gtk.glade
except:
	sys.exit(1)

import dbus

class OFart:
	def __init__(self):
		#load glade file
		self.gladefile="/usr/share/ofart/ofart.glade"
		self.wTree = gtk.glade.XML(self.gladefile,  "mainWindow")
		#set up main window
		self.window = self.wTree.get_widget("mainWindow")
		if (self.window):
			self.window.connect("destroy",  gtk.main_quit)
		eventDic = { "on_eventbox1_button_press_event" :  self.fart }
		self.wTree.signal_autoconnect(eventDic)

	def fart(self,  widget,  container):
		#todo
		print "parp"
		bus = dbus.SystemBus()
		audio =  bus.get_object("org.freesmartphone.odeviced",  "/org/freesmartphone/Device/Audio")
		iface = dbus.Interface(audio,  "org.freesmartphone.Device.Audio")
		iface.PlaySound("/usr/share/ofart/sounds/squeek.wav", 0, 3)


if __name__ == "__main__":
	oFart = OFart()
	gtk.main()
